### ISSUE TITLE
Loading game profiles that require an `initfs` key require the tool to be run with admin rights

### ISSUE THREAD

**Issue by HarGabt** [FrostyToolsuite/FrostyToolsuite#34]
### Please describe your issue

Enter a message...

### Were you using the Editor or the Mod Manager?

Editor

### Which version of the Editor/Mod Manager are you using ?

[1.0.0+c3a52c2ee2433e303c97210066cb27c5d2fb278b](https://github.com/FrostyToolsuite/FrostyToolsuite/actions/runs/11651638646)

### Has Frosty worked for you before? If so, did anything change ?

Doesn't matter

### Do you have a cracked/pirated version of the game?

No

### Have you extracted all of the zip's contents (files and folders) into an empty folder?

Yes

### Are you using FrostyFix or DatapathFix to fix launching if you didn't purchase the game on Origin?

No

### Which game(s) are you trying to mod?

Dead Space, Need For Speed Heat, Need For Speed Unbound

### Which operating system version are you using?

Windows 11

### Please provide a breakdown of the steps performed to produce the issue

- Start the tool without admin rights
- Load a game profile that requires initfs key
- Witness a crash with unhandled exception

### Please share the FULL error message

Unhandled exception: Client does not have required privileges. : 'F:\Frosty 2.0 (WIP) (ModExecutor)\FrostyCliShell\ThirdParty\oo2core.dll'
   at Interop.Kernel32.CreateSymbolicLink(String symlinkFileName, String targetFileName, Boolean isDirectory)
   at System.IO.File.CreateSymbolicLink(String path, String pathToTarget)
   at Frosty.Sdk.Managers.ResourceManager.Initialize()
   at Frosty.Program.LoadGame(String inGamePath, Int32 inPid)
   at Frosty.Program.<>c__DisplayClass0_0.<CreateBaseCommands>b__2(InvocationContext context)
   at System.CommandLine.Invocation.AnonymousCommandHandler.Invoke(InvocationContext context)
   at System.CommandLine.Invocation.AnonymousCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass17_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass19_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__18_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__5_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass8_0.<<UseExceptionHandler>b__0>d.MoveNext()

### If you're using the Mod Manager, have you tried applying only one mod? Did it work?

N/A

### If you're using the Mod Manager, please list the mods you're applying with

No mods

### Did you modify, remove, or add any plugins?

No

**Comment by wannkunstbeikor** [comment]
just changed the name a bit, bc the symlink is the issue not the initfskey, it just happens to be similar, since the games that use oodle which frosty creates a symlink for also have an encrypted initfs

**Comment by wannkunstbeikor** [comment]
u could create a helper app that is started with admin rights like v1 does, but this is ugly imo

**Comment by wannkunstbeikor** [comment]
not sure if there is a better way, but if there is i would prefer it
